### ISSUE TITLE
Currency Conversion

### ISSUE THREAD

**Issue by rebootcode** [Instamojo/Woo-Instamojo#17]
In one of my WordPress store, I have multi-currency setup and Dollar is default currency. Whenever any Indian buyer clicks "buy", It asks the same amount in Rs.

For an instance, if the product is 22$, It asks Rs. 22, which is wrong. Though there is already currency conversion setup in my store, and it works perfectly, but as soon as the user clicks on Pay, it gives the same amount in Rs. instead of dollar or conversion from dollar to INR.

Solution?

**Comment by ajitbohra** [comment]
@rebootcode as far as I know instamojo plugin will not do the conversion from dollar to rupee!

in past have to handle `$` and `rs` you can refer this blog post https://lubus.in/blog/how-to-sell-woocommerce-products-with-two-different-prices-77

**Comment by rebootcode** [comment]
I finally modified the plugin with my Code to do the currency conversion.

Thanks

**Comment by ajitbohra** [comment]
@rebootcode we can push that to the plugin would be helpful to others looking for the same.
