### ISSUE TITLE
Few doubts

### ISSUE THREAD

**Issue by ajitbohra** [Instamojo/Woo-Instamojo#4]
- can we accepts payment in currency other then INR or auto converts any payment to INR ?
- can we accept payments from customer outside india using instamojo ?.

If you can help me with this i guess we may have some improvements for plugin.

**Comment by saich** [comment]
- Instamojo can accept INR payments from international users also. Just note that international phone numbers should be prefixed with the ISD code (like, +911234567890), else the number could get rejected as invalid.
- Instamojo currently accepts INR currency only, and there is no in-built mechanism to convert other currency amounts to INR.

Hope this answers your queries.

**Comment by ajitbohra** [comment]
- Ok so lets consider a situation where user is from US with US Debit/Credit Card will he be able to make payment via instamojo ?
- If yes, so payment will be made in $ will that be converted to INR ?
